spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./db/testdb;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    com.donatasd.translator: debug
